spring:
  application:
    name: user-api
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: usersubr
    password: userspassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      max-lifetime: 100000
      connection-timeout: 30000
      pool-name: DividendsPostgreSql

infrastructure:
  http:
    auth:
      url:
