spring:
  application:
    name: user-api
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/usersapi
    username: usersubr
    password: userspassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      max-lifetime: 100000
      connection-timeout: 30000
  jpa:
    jpa:
      properties:
        hibernate:
          default_schema: usersapi_adm
          use-new-id-generator-mappings: false
          ddl-auto: none
      open-in-view: true
      hibernate:
        database-platform: org.postgresql.Driver
      show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: events.ap.eye@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs



server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024


infrastructure:
  http:
    auth:
      url:
