spring:
  application:
    name: user-api
  datasource:
    url: jdbc:postgresql://localhost:4000/users
    username: usersubr
    password: userspassword
    driver-class-name: org.postgresql.Driver

infrastructure:
  http:
    auth:
      url:
